version: '3.8'

services:
  node:
    image: node:16.8.0
    volumes:
      - .:/home/app:delegated
      - node_modules:/home/app/node_modules
    working_dir: /home/app
    tty: true

volumes:
 node_modules:
